### ISSUE TITLE
Assembly Instructions?

### ISSUE THREAD

**Issue by DanielArnett** [Roboy/DarkRoom#1]
Are there any tutorials on assembly, plugging the detector boards into the fpga, or connecting the FPGA to ROS? My lab is interested in this (awesome!) project, and integrating it into some of our work, and if there isn't a setup guide I'd be happy to help make one. There seems to be enough info on the Hackaday page, and your other GitHub pages.

Thanks for this awesome project! I've been showing it to all of my friends here at the Robotics Institute and they can't wait to try it out!

**Comment by letrend** [comment]
Connecting the sensors to the fpga is trivial. There is only one signal cable per sensor connected to the fpga. 

We haven't had much time documenting everything. But we're on it ;)

You can find one of our images here: http://roboy.org/dists/stable/main/binary/
Simply flash that onto a micro USB card (≥8gb):
sudo dd if=DE10_nano_lxce_4.1.33-ltsi-altera.img of=/dev/sdx bs=1M 

Setup environmental variables ROS_IP and ROS_MASTER_URI.
Start roscore on host. Start the node on the fpga. After catkin_make in Darkroom, source devel/setup.bash, then fire up rviz.

Thanks, really appreciate it. If you run into any trouble, let us know

**Comment by letrend** [comment]
Oh and you will obviously need to flash the sof/rbf onto the fpga

**Comment by DanielArnett** [comment]
Great, thank you! I've been showing this to everyone in the lab and we're all excited to try it. I'll share this with them and hopefully we can get this working in a few weeks. When we have it working I'll try to update the setup documentation on GitHub.

[Also I wrote a ROS node for the HTC Tracker as well, for anyone who doesn't have the time to fabricate their own tracker.](https://github.com/moon-wreckers/vive_tracker)

**Comment by letrend** [comment]
nice!

i updated the readme and cleaned up a little. sry for the mess in some parts, but this is under active development
